# Use the official Node.js image as the base image
FROM node:slim

# Set the working directory inside the container
WORKDIR /app

# COPY ./.npmrc ./
# Copy only package.json and package-lock.json to leverage Docker caching
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Expose the port the app runs on (e.g., 3000)
EXPOSE 3002

# Set the environment variable for production
ENV NODE_ENV=production

# Command to run the application
CMD ["npm", "start"]