### Get all orders
GET http://localhost:3002/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UuaGF0c2tldmljaEBnbWFpbC5jb20iLCJzdWIiOiJjYWMyZjU4MS02MWUyLTQxMmUtYmM4Ny1mYzk1MjNkZDVkOTYiLCJpYXQiOjE3NDQ2NTI5MjMsImV4cCI6MTc0NDczOTMyM30.xd-PdX-O2A-ZeGhHe147m8y4CNHU46XhYm_vRjai3ss

### Get user orders
GET http://localhost:3002/api/order/user/55e42da4-5885-4ed6-b3f4-3a509644afed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2VoYWNAcHJvdG9ubWFpbC5jb20iLCJzdWIiOiI1NWU0MmRhNC01ODg1LTRlZDYtYjNmNC0zYTUwOTY0NGFmZWQiLCJpYXQiOjE3NDUzMzY4MjQsImV4cCI6MTc0NTQyMzIyNH0.IypNLNUO4f39_ryPmip6EZ-Z5RznpzfR7-thZXsnm_w