# Use the official Node.js image as the base image
FROM node:slim

# Set the working directory inside the container
WORKDIR /app

# COPY ./.npmrc ./
# Copy only package.json and package-lock.json to leverage Docker caching
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Fix line endings and make the entrypoint script executable
RUN apt-get update && apt-get install -y dos2unix \
  && dos2unix ./docker-entrypoint.sh \
  && chmod +x ./docker-entrypoint.sh \
  && apt-get --purge remove -y dos2unix \
  && rm -rf /var/lib/apt/lists/*

# Build the application
RUN npm run build

# Expose the port the app runs on (e.g., 3000)
EXPOSE 3000

# Set the environment variable for production
ENV NODE_ENV=production
ENV DB_USE_SSL=false

# Set the entrypoint to our custom script
ENTRYPOINT ["./docker-entrypoint.sh"]

# Command to run the application (this gets passed to the entrypoint)
CMD ["npm", "start"]