import { DataSource } from 'typeorm';
import { Product } from '../entities/product.entity'; // adjust path as needed

export const seedProducts = async (dataSource: DataSource) => {
  const productRepository = dataSource.getRepository(Product);

  // Products data from CSV file
  const products = [
    {
      id: 1,
      name: 'Smartphone',
      description: 'Smartphone - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97',
      price: 254.09,
      categoryId: 1,
    },
    {
      id: 2,
      name: 'Bluetooth Speaker',
      description: 'Bluetooth Speaker - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1589256469067-ea99122bbdc4',
      price: 349.64,
      categoryId: 1,
    },
    {
      id: 3,
      name: 'Wireless Headphones',
      description: 'Wireless Headphones - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1612465289702-7c84b5258fde',
      price: 209.37,
      categoryId: 1,
    },
    {
      id: 4,
      name: 'Smartwatch',
      description: 'Smartwatch - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1632794716789-42d9995fb5b6',
      price: 126.82,
      categoryId: 1,
    },
    {
      id: 5,
      name: 'Drone',
      description: 'Drone - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108',
      price: 163.81,
      categoryId: 1,
    },
    {
      id: 6,
      name: 'Tablet',
      description: 'Tablet - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1623126908029-58cb08a2b272',
      price: 488.19,
      categoryId: 1,
    },
    {
      id: 7,
      name: 'Portable Charger',
      description: 'Portable Charger - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1706275787520-541d385ae221',
      price: 392.97,
      categoryId: 1,
    },
    {
      id: 8,
      name: 'LED TV',
      description: 'LED TV - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1614696131965-cc559b1ecad1',
      price: 146.96,
      categoryId: 1,
    },
    {
      id: 9,
      name: 'Digital Camera',
      description: 'Digital Camera - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1526413494904-7a15c807b00e',
      price: 407.99,
      categoryId: 1,
    },
    {
      id: 10,
      name: 'VR Headset',
      description: 'VR Headset - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1683821291789-c374b55e0cd2',
      price: 438.55,
      categoryId: 1,
    },
    {
      id: 11,
      name: 'LED Bulb',
      description: 'LED Bulb - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?LED%20Bulb',
      price: 219.63,
      categoryId: 2,
    },
    {
      id: 12,
      name: 'Smart Thermostat',
      description: 'Smart Thermostat - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Smart%20Thermostat',
      price: 307.46,
      categoryId: 2,
    },
    {
      id: 13,
      name: 'Power Drill',
      description: 'Power Drill - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Power%20Drill',
      price: 364.02,
      categoryId: 2,
    },
    {
      id: 14,
      name: 'Screwdriver Set',
      description: 'Screwdriver Set - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Screwdriver%20Set',
      price: 118.42,
      categoryId: 2,
    },
    {
      id: 15,
      name: 'Extension Cord',
      description: 'Extension Cord - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1610056494071-9373f12bf769',
      price: 202.54,
      categoryId: 2,
    },
    {
      id: 16,
      name: 'Wall Lamp',
      description: 'Wall Lamp - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Wall%20Lamp',
      price: 400.34,
      categoryId: 2,
    },
    {
      id: 17,
      name: 'Ceiling Fan',
      description: 'Ceiling Fan - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Ceiling%20Fan',
      price: 465.95,
      categoryId: 2,
    },
    {
      id: 18,
      name: 'Motion Sensor',
      description: 'Motion Sensor - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Motion%20Sensor',
      price: 463.68,
      categoryId: 2,
    },
    {
      id: 19,
      name: 'Toolbox',
      description: 'Toolbox - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Toolbox',
      price: 229.22,
      categoryId: 2,
    },
    {
      id: 20,
      name: 'Multimeter',
      description: 'Multimeter - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Multimeter',
      price: 279.9,
      categoryId: 2,
    },
    {
      id: 21,
      name: 'Gold Ring',
      description: 'Gold Ring - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Gold%20Ring',
      price: 483.26,
      categoryId: 3,
    },
    {
      id: 22,
      name: 'Silver Necklace',
      description: 'Silver Necklace - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Silver%20Necklace',
      price: 412.23,
      categoryId: 3,
    },
    {
      id: 23,
      name: 'Diamond Earrings',
      description: 'Diamond Earrings - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Diamond%20Earrings',
      price: 73.75,
      categoryId: 3,
    },
    {
      id: 24,
      name: 'Bracelet',
      description: 'Bracelet - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Bracelet',
      price: 96.2,
      categoryId: 3,
    },
    {
      id: 25,
      name: 'Watch',
      description: 'Watch - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Watch',
      price: 277.66,
      categoryId: 3,
    },
    {
      id: 26,
      name: 'Pendant',
      description: 'Pendant - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Pendant',
      price: 178.26,
      categoryId: 3,
    },
    {
      id: 27,
      name: 'Cufflinks',
      description: 'Cufflinks - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Cufflinks',
      price: 121.43,
      categoryId: 3,
    },
    {
      id: 28,
      name: 'Anklet',
      description: 'Anklet - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Anklet',
      price: 15.89,
      categoryId: 3,
    },
    {
      id: 29,
      name: 'Brooch',
      description: 'Brooch - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Brooch',
      price: 314.86,
      categoryId: 3,
    },
    {
      id: 30,
      name: 'Luxury Watch',
      description: 'Luxury Watch - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Luxury%20Watch',
      price: 439.78,
      categoryId: 3,
    },
    {
      id: 31,
      name: 'Puzzle',
      description: 'Puzzle - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Puzzle',
      price: 360.77,
      categoryId: 4,
    },
    {
      id: 32,
      name: 'RC Car',
      description: 'RC Car - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?RC%20Car',
      price: 12.75,
      categoryId: 4,
    },
    {
      id: 33,
      name: 'Action Figure',
      description: 'Action Figure - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Action%20Figure',
      price: 132.6,
      categoryId: 4,
    },
    {
      id: 34,
      name: 'Board Game',
      description: 'Board Game - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Board%20Game',
      price: 142.33,
      categoryId: 4,
    },
    {
      id: 35,
      name: 'Lego Set',
      description: 'Lego Set - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Lego%20Set',
      price: 447.65,
      categoryId: 4,
    },
    {
      id: 36,
      name: 'Yo-yo',
      description: 'Yo-yo - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Yo-yo',
      price: 303.47,
      categoryId: 4,
    },
    {
      id: 37,
      name: 'Stuffed Animal',
      description: 'Stuffed Animal - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Stuffed%20Animal',
      price: 193.03,
      categoryId: 4,
    },
    {
      id: 38,
      name: 'Dollhouse',
      description: 'Dollhouse - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Dollhouse',
      price: 74.7,
      categoryId: 4,
    },
    {
      id: 39,
      name: 'Drone Toy',
      description: 'Drone Toy - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Drone%20Toy',
      price: 163.36,
      categoryId: 4,
    },
    {
      id: 40,
      name: 'Building Blocks',
      description: 'Building Blocks - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Building%20Blocks',
      price: 422.32,
      categoryId: 4,
    },
    {
      id: 41,
      name: 'T-Shirt',
      description: 'T-Shirt - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475',
      price: 57.09,
      categoryId: 5,
    },
    {
      id: 42,
      name: 'Jeans',
      description: 'Jeans - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1602293589930-45aad59ba3ab',
      price: 94.19,
      categoryId: 5,
    },
    {
      id: 43,
      name: 'Jacket',
      description: 'Jacket - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea',
      price: 12.26,
      categoryId: 5,
    },
    {
      id: 44,
      name: 'Sneakers',
      description: 'Sneakers - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a',
      price: 201.17,
      categoryId: 5,
    },
    {
      id: 45,
      name: 'Dress',
      description: 'Dress - high quality and affordable.',
      imageUrl:
        'https://images.unsplash.com/flagged/photo-1585052201332-b8c0ce30972f?q=80&w=2670',
      price: 150.41,
      categoryId: 5,
    },
    {
      id: 46,
      name: 'Sweater',
      description: 'Sweater - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1574201635302-388dd92a4c3f',
      price: 292.6,
      categoryId: 5,
    },
    {
      id: 47,
      name: 'Scarf',
      description: 'Scarf - high quality and affordable.',
      imageUrl:
        'https://images.unsplash.com/photo-1609803384069-19f3e5a70e75?w=500',
      price: 439.67,
      categoryId: 5,
    },
    {
      id: 48,
      name: 'Hat',
      description: 'Hat - high quality and affordable.',
      imageUrl:
        'https://plus.unsplash.com/premium_photo-1671571592084-1fef547e09b5?w=500',
      price: 210.75,
      categoryId: 5,
    },
    {
      id: 49,
      name: 'Blazer',
      description: 'Blazer - high quality and affordable.',
      imageUrl:
        'https://images.unsplash.com/photo-1593030942428-a5451dca4b42?w=500',
      price: 291.44,
      categoryId: 5,
    },
    {
      id: 50,
      name: 'Skirt',
      description: 'Skirt - high quality and affordable.',
      imageUrl:
        'https://plus.unsplash.com/premium_photo-1671149028241-8e25ffee90dc',
      price: 227.27,
      categoryId: 5,
    },
    {
      id: 51,
      name: 'Lipstick',
      description: 'Lipstick - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Lipstick',
      price: 211.19,
      categoryId: 6,
    },
    {
      id: 52,
      name: 'Moisturizer',
      description: 'Moisturizer - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Moisturizer',
      price: 123.72,
      categoryId: 6,
    },
    {
      id: 53,
      name: 'Shampoo',
      description: 'Shampoo - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Shampoo',
      price: 210.16,
      categoryId: 6,
    },
    {
      id: 54,
      name: 'Face Cream',
      description: 'Face Cream - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Face%20Cream',
      price: 298.63,
      categoryId: 6,
    },
    {
      id: 55,
      name: 'Perfume',
      description: 'Perfume - high quality and affordable.',
      imageUrl: 'https://images.unsplash.com/photo-1557170334-a9632e77c6e4',
      price: 167.24,
      categoryId: 6,
    },
    {
      id: 56,
      name: 'Toothbrush',
      description: 'Toothbrush - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Toothbrush',
      price: 146.25,
      categoryId: 6,
    },
    {
      id: 57,
      name: 'Electric Razor',
      description: 'Electric Razor - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Electric%20Razor',
      price: 251.49,
      categoryId: 6,
    },
    {
      id: 58,
      name: 'Hair Dryer',
      description: 'Hair Dryer - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Hair%20Dryer',
      price: 233.2,
      categoryId: 6,
    },
    {
      id: 59,
      name: 'Sunscreen',
      description: 'Sunscreen - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Sunscreen',
      price: 122.65,
      categoryId: 6,
    },
    {
      id: 60,
      name: 'Makeup Kit',
      description: 'Makeup Kit - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Makeup%20Kit',
      price: 238.98,
      categoryId: 6,
    },
    {
      id: 61,
      name: 'Car Cover',
      description: 'Car Cover - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Car%20Cover',
      price: 464.22,
      categoryId: 7,
    },
    {
      id: 62,
      name: 'Motor Oil',
      description: 'Motor Oil - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Motor%20Oil',
      price: 92.58,
      categoryId: 7,
    },
    {
      id: 63,
      name: 'Tire Inflator',
      description: 'Tire Inflator - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Tire%20Inflator',
      price: 336.64,
      categoryId: 7,
    },
    {
      id: 64,
      name: 'Helmet',
      description: 'Helmet - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Helmet',
      price: 172.73,
      categoryId: 7,
    },
    {
      id: 65,
      name: 'Car Vacuum',
      description: 'Car Vacuum - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Car%20Vacuum',
      price: 480.92,
      categoryId: 7,
    },
    {
      id: 66,
      name: 'Phone Mount',
      description: 'Phone Mount - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Phone%20Mount',
      price: 332.09,
      categoryId: 7,
    },
    {
      id: 67,
      name: 'Dash Cam',
      description: 'Dash Cam - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Dash%20Cam',
      price: 92.83,
      categoryId: 7,
    },
    {
      id: 68,
      name: 'Seat Cover',
      description: 'Seat Cover - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Seat%20Cover',
      price: 38.16,
      categoryId: 7,
    },
    {
      id: 69,
      name: 'Steering Wheel Cover',
      description: 'Steering Wheel Cover - high quality and affordable.',
      imageUrl:
        'https://source.unsplash.com/featured/?Steering%20Wheel%20Cover',
      price: 137.67,
      categoryId: 7,
    },
    {
      id: 70,
      name: 'Jump Starter',
      description: 'Jump Starter - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Jump%20Starter',
      price: 320.74,
      categoryId: 7,
    },
    {
      id: 71,
      name: 'Tent',
      description: 'Tent - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Tent',
      price: 478.75,
      categoryId: 8,
    },
    {
      id: 72,
      name: 'Backpack',
      description: 'Backpack - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Backpack',
      price: 340.36,
      categoryId: 8,
    },
    {
      id: 73,
      name: 'Running Shoes',
      description: 'Running Shoes - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Running%20Shoes',
      price: 451.55,
      categoryId: 8,
    },
    {
      id: 74,
      name: 'Fitness Tracker',
      description: 'Fitness Tracker - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Fitness%20Tracker',
      price: 405.78,
      categoryId: 8,
    },
    {
      id: 75,
      name: 'Yoga Mat',
      description: 'Yoga Mat - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Yoga%20Mat',
      price: 258.64,
      categoryId: 8,
    },
    {
      id: 76,
      name: 'Water Bottle',
      description: 'Water Bottle - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Water%20Bottle',
      price: 112.1,
      categoryId: 8,
    },
    {
      id: 77,
      name: 'Bike Helmet',
      description: 'Bike Helmet - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Bike%20Helmet',
      price: 164.55,
      categoryId: 8,
    },
    {
      id: 78,
      name: 'Camping Stove',
      description: 'Camping Stove - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Camping%20Stove',
      price: 277.84,
      categoryId: 8,
    },
    {
      id: 79,
      name: 'Hiking Boots',
      description: 'Hiking Boots - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Hiking%20Boots',
      price: 329.7,
      categoryId: 8,
    },
    {
      id: 80,
      name: 'Swimsuit',
      description: 'Swimsuit - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Swimsuit',
      price: 245.09,
      categoryId: 8,
    },
    {
      id: 81,
      name: 'Laptop',
      description: 'Laptop - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Laptop',
      price: 358.16,
      categoryId: 9,
    },
    {
      id: 82,
      name: 'Mouse',
      description: 'Mouse - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Mouse',
      price: 128.01,
      categoryId: 9,
    },
    {
      id: 83,
      name: 'Keyboard',
      description: 'Keyboard - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Keyboard',
      price: 416.48,
      categoryId: 9,
    },
    {
      id: 84,
      name: 'Monitor',
      description: 'Monitor - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Monitor',
      price: 198.25,
      categoryId: 9,
    },
    {
      id: 85,
      name: 'Desk Lamp',
      description: 'Desk Lamp - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Desk%20Lamp',
      price: 106.84,
      categoryId: 9,
    },
    {
      id: 86,
      name: 'Office Chair',
      description: 'Office Chair - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Office%20Chair',
      price: 326.51,
      categoryId: 9,
    },
    {
      id: 87,
      name: 'USB Hub',
      description: 'USB Hub - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?USB%20Hub',
      price: 211.46,
      categoryId: 9,
    },
    {
      id: 88,
      name: 'Webcam',
      description: 'Webcam - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Webcam',
      price: 319.27,
      categoryId: 9,
    },
    {
      id: 89,
      name: 'Printer',
      description: 'Printer - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Printer',
      price: 46.55,
      categoryId: 9,
    },
    {
      id: 90,
      name: 'Router',
      description: 'Router - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Router',
      price: 275.69,
      categoryId: 9,
    },
    {
      id: 91,
      name: 'Blender',
      description: 'Blender - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Blender',
      price: 444.12,
      categoryId: 10,
    },
    {
      id: 92,
      name: 'Microwave',
      description: 'Microwave - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Microwave',
      price: 89.63,
      categoryId: 10,
    },
    {
      id: 93,
      name: 'Coffee Maker',
      description: 'Coffee Maker - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Coffee%20Maker',
      price: 172.81,
      categoryId: 10,
    },
    {
      id: 94,
      name: 'Cutlery Set',
      description: 'Cutlery Set - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Cutlery%20Set',
      price: 152.17,
      categoryId: 10,
    },
    {
      id: 95,
      name: 'Dish Rack',
      description: 'Dish Rack - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Dish%20Rack',
      price: 85.35,
      categoryId: 10,
    },
    {
      id: 96,
      name: 'Toaster',
      description: 'Toaster - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Toaster',
      price: 41.4,
      categoryId: 10,
    },
    {
      id: 97,
      name: 'Rice Cooker',
      description: 'Rice Cooker - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Rice%20Cooker',
      price: 38.45,
      categoryId: 10,
    },
    {
      id: 98,
      name: 'Cookware Set',
      description: 'Cookware Set - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Cookware%20Set',
      price: 484.54,
      categoryId: 10,
    },
    {
      id: 99,
      name: 'Water Filter',
      description: 'Water Filter - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Water%20Filter',
      price: 16.31,
      categoryId: 10,
    },
    {
      id: 100,
      name: 'Vacuum Cleaner',
      description: 'Vacuum Cleaner - high quality and affordable.',
      imageUrl: 'https://source.unsplash.com/featured/?Vacuum%20Cleaner',
      price: 273.5,
      categoryId: 10,
    },
  ];

  await productRepository.save(products);
  console.log(`✅ Seeded ${products.length} products.`);
};
