GET http://localhost:3000/api/product/list/1,15

###
POST http://localhost:3000/api/product-rating
Content-Type: application/json

{
  "userId": "cac2f581-61e2-412e-bc87-fc9523dd5d96",
  "ratingId": 1,
  "productId": 1,
  "ratingDescription": "Exelent product!!!"
}

###
GET http://localhost:3000/api/product-rating/1
Content-Type: application/json